---
title: "Kaggle-Bike Sharing Demand"
author: "Gaurav Bansal"
date: "Friday, August 15, 2014"
output:
  pdf_document:
    fig_caption: no
    fig_height: 4
    fig_width: 6.5
    toc_depth: 1
---

```{r, echo=TRUE}
#Reding the file
bike <- read.csv("train.csv")
str(bike)
```

```{r, echo=TRUE}
#changing datetime format
bike$datetime <- as.POSIXlt(as.character(bike$datetime))
#basic EDA
summary(bike)
```

```{r, echo=TRUE}
#looking for outliers
par(mfrow=c(1,3))
boxplot(bike$casual,xlab="Casual")
boxplot(bike$registered,xlab="registered")
boxplot(bike$count,xlab="count")
```

```{r, echo=TRUE}
#looking for outliers with variables
par(mfrow=c(1,1))
boxplot(count~season,bike,xlab="season",ylab="count")
boxplot(count~holiday,bike,xlab="holiday",ylab="count")
boxplot(count~workingday,bike,xlab="workingday",ylab="count")
boxplot(count~weather,bike,xlab="weather",ylab="count")
plot(bike$datetime,bike$count,type="l",xlab="year",ylab="count")
```

```{r, echo=TRUE}
#corelation between various variables
cor(bike[,c(-1,-10,-11,-13)])
```
