bike <- read.csv("train.csv")
bike$datetime <- as.POSIXlt(as.character(bike$datetime))
bike$year <- as.numeric(format(bike$datetime,"%Y"))
bike$month <- as.numeric(format(bike$datetime,"%m"))
bike$date <- as.numeric(format(bike$datetime,"%d"))
bike$hour <- as.numeric(format(bike$datetime,"%H"))
bike$day <- weekdays(bike$datetime)
bike_jan <- subset(bike,bike$year==2011 & bike$month==1)
write.csv(bike_jan,"bike_jan.csv")
